// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATiTGBGLR0Wshz2lARERODyb9SPy7XxfA',
    appId: '1:804177700433:web:4480d480824ec2d9197a70',
    messagingSenderId: '804177700433',
    projectId: 'sistema-de-incidencias-832c1',
    authDomain: 'sistema-de-incidencias-832c1.firebaseapp.com',
    databaseURL: 'https://sistema-de-incidencias-832c1-default-rtdb.firebaseio.com',
    storageBucket: 'sistema-de-incidencias-832c1.appspot.com',
    measurementId: 'G-N8RT9JX7J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqkt5Gn92dbifmi2Iopa3CA8E7L52z_m4',
    appId: '1:804177700433:android:e3ab075cadd03580197a70',
    messagingSenderId: '804177700433',
    projectId: 'sistema-de-incidencias-832c1',
    databaseURL: 'https://sistema-de-incidencias-832c1-default-rtdb.firebaseio.com',
    storageBucket: 'sistema-de-incidencias-832c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9AsrkH8u8nCz_4VWmhWnpHRr5VlEhAPM',
    appId: '1:804177700433:ios:27983625d38939dc197a70',
    messagingSenderId: '804177700433',
    projectId: 'sistema-de-incidencias-832c1',
    databaseURL: 'https://sistema-de-incidencias-832c1-default-rtdb.firebaseio.com',
    storageBucket: 'sistema-de-incidencias-832c1.appspot.com',
    androidClientId: '804177700433-3jnbufu979ikiggj8c75emmgl0uta75p.apps.googleusercontent.com',
    iosClientId: '804177700433-koc05sqa5ad7q861ti0hfmc8kcse4u4b.apps.googleusercontent.com',
    iosBundleId: 'com.credencialesqr.maestros.maestros',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9AsrkH8u8nCz_4VWmhWnpHRr5VlEhAPM',
    appId: '1:804177700433:ios:9b0ce38b08437e5b197a70',
    messagingSenderId: '804177700433',
    projectId: 'sistema-de-incidencias-832c1',
    databaseURL: 'https://sistema-de-incidencias-832c1-default-rtdb.firebaseio.com',
    storageBucket: 'sistema-de-incidencias-832c1.appspot.com',
    androidClientId: '804177700433-3jnbufu979ikiggj8c75emmgl0uta75p.apps.googleusercontent.com',
    iosClientId: '804177700433-e8jkmposev7lbuq6silt4uq19a2lq8as.apps.googleusercontent.com',
    iosBundleId: 'com.credencialesqr.maestros.maestros.RunnerTests',
  );
}
